version: "3.3"
services:
  mkdocs-material:
    stdin_open: true
    tty: true
    volumes:
      - ~/.ssh:/root/.ssh
      - ${PWD}:/docs
    image: squidfunk/mkdocs-material
    command: gh-deploy
networks: {}